name: anti-slop
description: A GitHub action that detects and automatically closes low-quality and AI slop PRs.
author: peaklabs-dev

branding:
  icon: shield
  color: orange

runs:
  using: node24
  main: dist/index.mjs
