name: anti-slop
description: A GitHub action that detects and automatically closes low-quality and AI slop PRs.
author: peaklabs-dev

branding:
  icon: slash
  color: orange

inputs:
  # Repo Auth Token
  github-token:
    description: GitHub token used to authenticate API requests.
    required: true
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.mjs
