const COMMENT_PREFIXES_BY_LANGUAGE: [string[], string[]][] = [
    [
        [
            "c",
            "cjs",
            "cpp",
            "cs",
            "css",
            "dart",
            "go",
            "h",
            "hpp",
            "java",
            "js",
            "jsx",
            "kt",
            "less",
            "mjs",
            "php",
            "proto",
            "rs",
            "scala",
            "scss",
            "swift",
            "ts",
            "tsx",
            "zig",
        ],
        ["//", "/*", "*", "{/*"],
    ],
    [
        [
            "bash",
            "cmake",
            "coffee",
            "cr",
            "ex",
            "jl",
            "nim",
            "pl",
            "ps1",
            "py",
            "r",
            "rb",
            "sh",
            "tf",
            "toml",
            "yaml",
            "yml",
            "zsh",
        ],
        ["#"],
    ],
    [["ada", "elm", "hs", "lua", "sql", "vhdl"], ["--"]],
    [
        ["htm", "html", "svg", "xml"],
        ["<!--", "-->"],
    ],
    [
        ["astro", "svelte", "vue"],
        ["//", "/*", "*", "{/*", "<!--", "-->"],
    ],
    [["asm", "clj", "cljs", "el", "ini", "lisp", "rkt", "scm"], [";"]],
    [["erl", "pro", "sty", "tex"], ["%"]],
    [["f", "f90", "f95", "for"], ["!"]],
];

export const commentPrefixesByExtension: Map<string, string[]> = new Map(
    COMMENT_PREFIXES_BY_LANGUAGE.flatMap(([extensions, prefixes]) =>
        extensions.map((extension): [string, string[]] => [extension, prefixes]),
    ),
);
